const timetable={MON:[['09:00','Calculus I','Room 201','Dr. Ali'],['10:00','Object Oriented Programming','Lab 03','Dr. Ahmed'],['12:00','Pakistan Studies','Room 105','Ms. Hina']],TUE:[['09:00','Physics','Lab 02','Dr. Usman'],['11:00','English Composition','Room 112','Ms. Sara']],WED:[['10:00','Object Oriented Programming','Lab 03','Dr. Ahmed'],['12:00','Calculus I','Room 201','Dr. Ali']],THU:[['09:00','Physics','Lab 02','Dr. Usman'],['11:00','ICT','Lab 01','Mr. Hamza']],FRI:[['10:00','English Composition','Room 112','Ms. Sara'],['12:00','Pakistan Studies','Room 105','Ms. Hina']]};
let tasks=JSON.parse(localStorage.getItem('ptutTasks')||'null')||[{title:'Complete C++ Exercise 6.5',due:'Today · 11:59 PM',subject:'Object Oriented Programming',done:false},{title:'Prepare Physics Lab Manual',due:'Tomorrow · 6:00 PM',subject:'Physics',done:false},{title:'Read Chapter 3 — Calculus',due:'8 Oct · 8:00 PM',subject:'Calculus I',done:false},{title:'Submit ICT Assignment',due:'2 Oct · Completed',subject:'ICT',done:true}];
const exams=[['15','OCT','C++ Programming','10:00 AM','Hall A'],['21','OCT','Physics','09:00 AM','Lab 02'],['27','OCT','Calculus I','11:00 AM','Hall B']];
const announcements=[['Today · 9:10 AM','Mid-Semester Examination Schedule','The provisional mid-semester examination schedule has been uploaded. Please check your course and report any conflict to your department.'],['Yesterday','University Timing Update','Classes will follow the revised Monday schedule from next week. Students should check their section timetable.'],['2 Oct','Student Society Registrations','Registrations for student societies and campus activities are now open.']];
function navigate(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));document.getElementById(page).classList.add('active-page');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={dashboard:'Good afternoon, Fazeel 👋',timetable:'Your weekly timetable',tasks:'Your tasks & assignments',exams:'Upcoming exams',announcements:'PTUT campus announcements',profile:'Your profile'};document.getElementById('pageTitle').textContent=titles[page];document.getElementById('sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(x=>x.addEventListener('click',()=>navigate(x.dataset.page)));document.getElementById('menuBtn').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
function renderToday(){document.getElementById('todayList').innerHTML=timetable.MON.map((c,i)=>`<div class="today-row ${i===1?'current':''}"><div class="time">${c[0]} ${i===0?'— 09:50':i===1?'— 11:30':'— 1:30'}</div><div class="class-name">${c[1]}<small>${c[3]}</small></div><div class="room">⌖ ${c[2]}</div></div>`).join('')}
function taskHTML(t,i){return `<div class="task-card"><div class="task-top"><button class="check ${t.done?'done':''}" onclick="toggleTask(${i})">${t.done?'✓':''}</button><span class="tag">${t.subject}</span></div><h3 style="${t.done?'text-decoration:line-through;color:#94a3b8':''}">${t.title}</h3><p>${t.due}</p></div>`}
function renderTasks(){document.getElementById('taskPage').innerHTML=tasks.map(taskHTML).join('');document.getElementById('dashboardTasks').innerHTML=tasks.filter(x=>!x.done).slice(0,3).map(t=>`<div class="mini-item"><div><strong>${t.title}</strong><span>${t.subject}</span></div><span>${t.due}</span></div>`).join('');document.getElementById('taskBadge').textContent=tasks.filter(x=>!x.done).length;localStorage.setItem('ptutTasks',JSON.stringify(tasks))}
function toggleTask(i){tasks[i].done=!tasks[i].done;renderTasks();showToast(tasks[i].done?'Task completed ✓':'Task reopened')}
function addTask(){const title=prompt('Task title:');if(!title)return;tasks.unshift({title,due:'Today · 11:59 PM',subject:'General',done:false});renderTasks();showToast('Task added')}
function renderExams(){document.getElementById('examGrid').innerHTML=exams.map(e=>`<div class="exam-card"><div class="exam-date">${e[0]} <span>${e[1]}</span></div><h3>${e[2]}</h3><p>🕙 ${e[3]} · ⌖ ${e[4]}</p></div>`).join('')}
function announcementHTML(a){return `<article class="announcement"><div class="meta">${a[0]} · PTUT Administration</div><h3>${a[1]}</h3><p>${a[2]}</p></article>`}
function renderAnnouncements(){document.getElementById('announcementPage').innerHTML=announcements.map(announcementHTML).join('');document.getElementById('dashboardAnnouncements').innerHTML=announcements.slice(0,3).map(a=>`<div class="mini-item"><div><strong>${a[1]}</strong><span>${a[0]}</span></div></div>`).join('')}
function renderSchedule(){document.getElementById('scheduleBoard').innerHTML=Object.entries(timetable).map(([day,items])=>`<div class="day-col"><div class="day-head">${day}</div>${items.map(c=>`<div class="slot"><strong>${c[1]}</strong><span>🕙 ${c[0]}</span><span>⌖ ${c[2]}</span><em>${c[3]}</em></div>`).join('')}</div>`).join('')}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
renderToday();renderTasks();renderExams();renderAnnouncements();renderSchedule();
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});
